//! Metadata Service — shared object metadata backed by Redis.

use crate::config::Config;
use crate::error::{KVError, Result};
use crate::metrics::Metrics;
use parking_lot::Mutex;
use redis::Commands;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::sync::OnceLock;
use std::time::Duration;
use std::time::Instant;

#[cfg(test)]
use std::collections::HashMap;

const BLOCK_META_SEGMENT: &str = "block_meta";
const GENERATION_SEGMENT: &str = "generation";
const GC_DUE_SEGMENT: &str = "gc:due";
const GC_INFLIGHT_SEGMENT: &str = "gc:inflight";
const GC_TASK_SEGMENT: &str = "gc:task:";

fn default_object_generation() -> u64 {
    1
}

fn default_layout_version() -> u64 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ChunkLocation {
    pub stripe_index: u32,
    pub node_id: String,
    pub grpc_endpoint: String,
    pub rdma_endpoint: String,
    pub device_id: u32,
    pub storage_handle: String,
    pub offset: u64,
    pub length: u64,
    /// xxh3-64 checksum of the physical stripe, encoded as lowercase hexadecimal.
    #[serde(default)]
    pub checksum: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StripingInfo {
    /// Chunk size (bytes)
    pub chunk_size: u64,
    /// device_id for each chunk, indexed by chunk 0..N
    pub chunk_devices: Vec<u32>,
    /// File path (absolute) for each chunk
    pub chunk_paths: Vec<String>,
    /// Total raw data size
    pub total_size: u64,
    /// Actual per-chunk placement frozen at write time.
    ///
    /// May be empty for legacy metadata; when empty, fall back to local-node
    /// placement derived from chunk_paths/chunk_devices.
    #[serde(default)]
    pub chunk_locations: Vec<ChunkLocation>,
    /// xxh3-64 checksum for each chunk, indexed by chunk 0..N.
    ///
    /// Empty means the object was written while optional stripe integrity was disabled.
    #[serde(default)]
    pub chunk_checksums: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockMeta {
    pub device_id: u32,
    pub file_path: String,
    pub size: u64,
    /// Opaque read handle generated by the server. Clients only pass it back;
    /// they do not interpret the internal format.
    #[serde(default)]
    pub object_handle: String,
    /// Content generation of the same object key. New objects start at 1 and
    /// increment on overwrite.
    #[serde(default = "default_object_generation")]
    pub object_generation: u64,
    /// Content identity token generated at write time. A lightweight etag —
    /// GET requests are not required to recompute a hash over the whole object.
    #[serde(default)]
    pub content_etag: String,
    /// Physical layout version. Increments when rebalance/migration changes
    /// only the layout; it does not indicate content changes.
    #[serde(default = "default_layout_version")]
    pub layout_version: u64,
    pub created_at: i64,
    pub last_accessed_at: i64,
    pub ttl_seconds: i64,
    pub num_tokens: i32,
    pub num_layers: i32,
    pub dtype: String,
    pub compressed: bool,
    /// When Some, the value is striped across multiple chunks
    #[serde(default)]
    pub striping: Option<StripingInfo>,
}

impl BlockMeta {
    /// Return true when the object has a positive TTL and its creation timestamp is past expiry.
    pub fn is_expired_at(&self, now: i64) -> bool {
        self.ttl_seconds > 0
            && self
                .created_at
                .checked_add(self.ttl_seconds)
                .map(|expires_at| expires_at <= now)
                .unwrap_or(true)
    }

    /// Return true when the object is expired at the current wall-clock timestamp.
    pub fn is_expired(&self) -> bool {
        self.is_expired_at(chrono::Utc::now().timestamp())
    }
}

/// A durable request to reclaim a generation that is no longer referenced by
/// current metadata. The complete placement is retained for crash-safe cleanup.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GcTask {
    pub id: String,
    pub key: String,
    pub retired: BlockMeta,
    pub not_before: i64,
    pub attempts: u32,
}

enum MetadataBackend {
    Redis(RedisMetadataBackend),
    #[cfg(test)]
    Memory(MemoryMetadataBackend),
}

pub struct MetadataService {
    backend: MetadataBackend,
}

impl MetadataService {
    pub fn new(config: &Config) -> Result<Self> {
        Self::new_with_metrics(config, None)
    }

    pub fn new_with_metrics(config: &Config, metrics: Option<Arc<Metrics>>) -> Result<Self> {
        #[cfg(test)]
        if config.metadata.redis_url.starts_with("memory://") {
            return Ok(Self {
                backend: MetadataBackend::Memory(MemoryMetadataBackend::for_url(
                    &config.metadata.redis_url,
                )),
            });
        }

        Ok(Self {
            backend: MetadataBackend::Redis(RedisMetadataBackend::new(config, metrics)?),
        })
    }

    // ===== Block Meta =====

    pub fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.put_block(key, meta),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.put_block(key, meta),
        }
    }

    pub fn put_block_if_absent(&self, key: &str, meta: &BlockMeta) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.put_block_if_absent(key, meta),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.put_block_if_absent(key, meta),
        }
    }

    /// Atomically publish `meta` and enqueue the previously visible generation
    /// for delayed physical reclamation.
    pub fn replace_block(
        &self,
        key: &str,
        meta: &BlockMeta,
        not_before: i64,
    ) -> Result<Option<BlockMeta>> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.replace_block(key, meta, not_before),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.replace_block(key, meta, not_before),
        }
    }

    /// Atomically make the object unreachable and enqueue its physical layout.
    pub fn retire_block(&self, key: &str, not_before: i64) -> Result<Option<BlockMeta>> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.retire_block(key, not_before),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.retire_block(key, not_before),
        }
    }

    /// Retire only the metadata version observed by the caller.
    pub fn retire_block_if_matches(
        &self,
        key: &str,
        expected: &BlockMeta,
        not_before: i64,
    ) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => {
                backend.retire_block_if_matches(key, expected, not_before)
            }
            #[cfg(test)]
            MetadataBackend::Memory(backend) => {
                backend.retire_block_if_matches(key, expected, not_before)
            }
        }
    }

    /// Claim due tasks under a time-bounded lease.
    pub fn take_due_gc_tasks(
        &self,
        now: i64,
        limit: usize,
        lease_seconds: u64,
    ) -> Result<Vec<GcTask>> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.take_due_gc_tasks(now, limit, lease_seconds),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => {
                backend.take_due_gc_tasks(now, limit, lease_seconds)
            }
        }
    }

    pub fn complete_gc_task(&self, task_id: &str) -> Result<()> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.complete_gc_task(task_id),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.complete_gc_task(task_id),
        }
    }

    pub fn reschedule_gc_task(&self, task: &GcTask) -> Result<()> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.reschedule_gc_task(task),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.reschedule_gc_task(task),
        }
    }

    pub fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.get_block(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.get_block(key),
        }
    }

    pub fn delete_block(&self, key: &str) -> Result<()> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.delete_block(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.delete_block(key),
        }
    }

    /// Delete metadata only when the stored value still matches the expected object metadata.
    pub fn delete_block_if_matches(&self, key: &str, expected: &BlockMeta) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.delete_block_if_matches(key, expected),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.delete_block_if_matches(key, expected),
        }
    }

    pub fn exists_block(&self, key: &str) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.exists_block(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.exists_block(key),
        }
    }

    pub fn next_generation(&self, key: &str) -> Result<u64> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.next_generation(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.next_generation(key),
        }
    }

    #[cfg(test)]
    pub fn fail_next_put_for_test(&self) {
        if let MetadataBackend::Memory(backend) = &self.backend {
            backend.fail_next_put();
        }
    }
}

struct RedisMetadataBackend {
    client: redis::Client,
    prefix: String,
    connect_timeout: Duration,
    command_timeout: Duration,
    connection: Mutex<redis::Connection>,
    metrics: Option<Arc<Metrics>>,
}

impl RedisMetadataBackend {
    fn new(config: &Config, metrics: Option<Arc<Metrics>>) -> Result<Self> {
        let client = redis::Client::open(config.metadata.redis_url.as_str())
            .map_err(|e| KVError::Metadata(format!("open Redis client: {}", e)))?;
        let connect_timeout = Duration::from_millis(config.metadata.redis_connect_timeout_ms);
        let command_timeout = Duration::from_millis(config.metadata.redis_command_timeout_ms);
        let mut connection = Self::connect(&client, connect_timeout, command_timeout)?;
        redis::cmd("PING")
            .query::<String>(&mut connection)
            .map_err(|e| KVError::Metadata(format!("ping Redis metadata store: {}", e)))?;

        Ok(Self {
            client,
            prefix: config.metadata.redis_key_prefix.clone(),
            connect_timeout,
            command_timeout,
            connection: Mutex::new(connection),
            metrics,
        })
    }

    fn connect(
        client: &redis::Client,
        connect_timeout: Duration,
        command_timeout: Duration,
    ) -> Result<redis::Connection> {
        let connection = client
            .get_connection_with_timeout(connect_timeout)
            .map_err(|e| {
                KVError::Metadata(format!(
                    "connect Redis metadata store within {} ms: {}",
                    connect_timeout.as_millis(),
                    e
                ))
            })?;
        connection
            .set_read_timeout(Some(command_timeout))
            .map_err(|e| KVError::Metadata(format!("set Redis read timeout: {}", e)))?;
        connection
            .set_write_timeout(Some(command_timeout))
            .map_err(|e| KVError::Metadata(format!("set Redis write timeout: {}", e)))?;
        Ok(connection)
    }

    fn run_with_reconnect<T, F>(&self, op: &str, mut command: F) -> Result<T>
    where
        F: FnMut(&mut redis::Connection) -> redis::RedisResult<T>,
    {
        let started = self.metrics.as_ref().map(|_| Instant::now());
        let mut connection = self.connection.lock();
        let result = match command(&mut connection) {
            Ok(value) => Ok(value),
            Err(first_error) => {
                tracing::warn!(
                    "Redis metadata command {} failed, reconnecting once: {}",
                    op,
                    first_error
                );
                if let Some(metrics) = &self.metrics {
                    metrics.record_metadata_reconnect();
                }
                match Self::connect(&self.client, self.connect_timeout, self.command_timeout) {
                    Ok(mut new_connection) => match command(&mut new_connection) {
                        Ok(value) => {
                            *connection = new_connection;
                            Ok(value)
                        }
                        Err(second_error) => Err(KVError::Metadata(format!(
                            "redis {} failed after reconnect: {}; first error: {}",
                            op, second_error, first_error
                        ))),
                    },
                    Err(reconnect_error) => Err(reconnect_error),
                }
            }
        };
        if let (Some(metrics), Some(started)) = (&self.metrics, started) {
            metrics.record_metadata_operation(
                op,
                if result.is_ok() { "ok" } else { "error" },
                started.elapsed().as_secs_f64(),
            );
        }
        result
    }

    fn block_key(&self, key: &str) -> String {
        format!("{}{}:{}", self.prefix, BLOCK_META_SEGMENT, key)
    }

    fn generation_key(&self, key: &str) -> String {
        format!("{}{}:{}", self.prefix, GENERATION_SEGMENT, key)
    }

    fn gc_due_key(&self) -> String {
        format!("{}{}", self.prefix, GC_DUE_SEGMENT)
    }

    fn gc_inflight_key(&self) -> String {
        format!("{}{}", self.prefix, GC_INFLIGHT_SEGMENT)
    }

    fn gc_task_prefix(&self) -> String {
        format!("{}{}", self.prefix, GC_TASK_SEGMENT)
    }

    fn serialize(meta: &BlockMeta) -> Result<Vec<u8>> {
        serde_json::to_vec(meta).map_err(|e| KVError::Metadata(format!("serialize: {}", e)))
    }

    fn deserialize(bytes: &[u8]) -> Result<BlockMeta> {
        serde_json::from_slice(bytes).map_err(|e| KVError::Metadata(format!("deserialize: {}", e)))
    }

    fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        let redis_key = self.block_key(key);
        let bytes = Self::serialize(meta)?;
        self.run_with_reconnect("put_block", |connection| {
            connection.set::<_, _, ()>(&redis_key, &bytes)
        })
    }

    fn put_block_if_absent(&self, key: &str, meta: &BlockMeta) -> Result<bool> {
        let redis_key = self.block_key(key);
        let bytes = Self::serialize(meta)?;
        let result = self.run_with_reconnect("put_block_if_absent", |connection| {
            redis::cmd("SET")
                .arg(&redis_key)
                .arg(&bytes)
                .arg("NX")
                .query::<Option<String>>(connection)
        })?;
        Ok(result.is_some())
    }

    fn replace_block(
        &self,
        key: &str,
        meta: &BlockMeta,
        not_before: i64,
    ) -> Result<Option<BlockMeta>> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local old = redis.call("GET", KEYS[1])
            redis.call("SET", KEYS[1], ARGV[1])
            if old then
                local id = redis.sha1hex(KEYS[1] .. ":" .. old)
                local task_key = ARGV[2] .. id
                local task = cjson.encode({id=id, key=ARGV[3], retired=cjson.decode(old), not_before=tonumber(ARGV[4]), attempts=0})
                redis.call("HSET", task_key, "payload", task)
                redis.call("ZADD", KEYS[2], tonumber(ARGV[4]), task_key)
            end
            return old
            "#,
            )
        });
        let block_key = self.block_key(key);
        let due_key = self.gc_due_key();
        let bytes = Self::serialize(meta)?;
        let old =
            self.run_with_reconnect("replace block metadata and enqueue GC", |connection| {
                script
                    .key(&block_key)
                    .key(&due_key)
                    .arg(&bytes)
                    .arg(self.gc_task_prefix())
                    .arg(key)
                    .arg(not_before)
                    .invoke::<Option<Vec<u8>>>(connection)
            })?;
        old.as_deref().map(Self::deserialize).transpose()
    }

    fn retire_block(&self, key: &str, not_before: i64) -> Result<Option<BlockMeta>> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local old = redis.call("GET", KEYS[1])
            if old then
                redis.call("DEL", KEYS[1])
                local id = redis.sha1hex(KEYS[1] .. ":" .. old)
                local task_key = ARGV[1] .. id
                local task = cjson.encode({id=id, key=ARGV[2], retired=cjson.decode(old), not_before=tonumber(ARGV[3]), attempts=0})
                redis.call("HSET", task_key, "payload", task)
                redis.call("ZADD", KEYS[2], tonumber(ARGV[3]), task_key)
            end
            return old
            "#,
            )
        });
        let block_key = self.block_key(key);
        let due_key = self.gc_due_key();
        let old =
            self.run_with_reconnect("retire block metadata and enqueue GC", |connection| {
                script
                    .key(&block_key)
                    .key(&due_key)
                    .arg(self.gc_task_prefix())
                    .arg(key)
                    .arg(not_before)
                    .invoke::<Option<Vec<u8>>>(connection)
            })?;
        old.as_deref().map(Self::deserialize).transpose()
    }

    fn retire_block_if_matches(
        &self,
        key: &str,
        expected: &BlockMeta,
        not_before: i64,
    ) -> Result<bool> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local current = redis.call("GET", KEYS[1])
            if not current then return 0 end
            local expected = cjson.decode(ARGV[1])
            local actual = cjson.decode(current)
            if actual["object_handle"] ~= expected["object_handle"]
                or actual["object_generation"] ~= expected["object_generation"]
                or actual["layout_version"] ~= expected["layout_version"]
                or actual["content_etag"] ~= expected["content_etag"]
                or actual["size"] ~= expected["size"] then
                return 0
            end
            redis.call("DEL", KEYS[1])
            local id = redis.sha1hex(KEYS[1] .. ":" .. current)
            local task_key = ARGV[2] .. id
            local task = cjson.encode({id=id, key=ARGV[3], retired=actual, not_before=tonumber(ARGV[4]), attempts=0})
            redis.call("HSET", task_key, "payload", task)
            redis.call("ZADD", KEYS[2], tonumber(ARGV[4]), task_key)
            return 1
            "#,
            )
        });
        let expected = Self::serialize(expected)?;
        let block_key = self.block_key(key);
        let due_key = self.gc_due_key();
        let retired = self.run_with_reconnect("retire matching block metadata", |connection| {
            script
                .key(&block_key)
                .key(&due_key)
                .arg(&expected)
                .arg(self.gc_task_prefix())
                .arg(key)
                .arg(not_before)
                .invoke::<i32>(connection)
        })?;
        Ok(retired == 1)
    }

    fn take_due_gc_tasks(&self, now: i64, limit: usize, lease_seconds: u64) -> Result<Vec<GcTask>> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let script = SCRIPT.get_or_init(|| redis::Script::new(r#"
            local expired = redis.call("ZRANGEBYSCORE", KEYS[2], "-inf", ARGV[1])
            for _, task_key in ipairs(expired) do
                if redis.call("ZREM", KEYS[2], task_key) == 1 then
                    redis.call("ZADD", KEYS[1], ARGV[1], task_key)
                end
            end
            local task_keys = redis.call("ZRANGEBYSCORE", KEYS[1], "-inf", ARGV[1], "LIMIT", 0, ARGV[2])
            local payloads = {}
            for _, task_key in ipairs(task_keys) do
                if redis.call("ZREM", KEYS[1], task_key) == 1 then
                    local payload = redis.call("HGET", task_key, "payload")
                    if payload then
                        redis.call("ZADD", KEYS[2], tonumber(ARGV[1]) + tonumber(ARGV[3]), task_key)
                        table.insert(payloads, payload)
                    end
                end
            end
            return payloads
        "#));
        let due_key = self.gc_due_key();
        let inflight_key = self.gc_inflight_key();
        let payloads = self.run_with_reconnect("claim due GC tasks", |connection| {
            script
                .key(&due_key)
                .key(&inflight_key)
                .arg(now)
                .arg(limit)
                .arg(lease_seconds)
                .invoke::<Vec<Vec<u8>>>(connection)
        })?;
        payloads
            .into_iter()
            .map(|payload| {
                serde_json::from_slice(&payload)
                    .map_err(|e| KVError::Metadata(format!("deserialize GC task: {}", e)))
            })
            .collect()
    }

    fn complete_gc_task(&self, task_id: &str) -> Result<()> {
        let task_key = format!("{}{}", self.gc_task_prefix(), task_id);
        self.run_with_reconnect("complete GC task", |connection| {
            let _: () = redis::cmd("ZREM")
                .arg(self.gc_inflight_key())
                .arg(&task_key)
                .query(connection)?;
            redis::cmd("DEL").arg(&task_key).query::<()>(connection)
        })
    }

    fn reschedule_gc_task(&self, task: &GcTask) -> Result<()> {
        let task_key = format!("{}{}", self.gc_task_prefix(), task.id);
        let payload = serde_json::to_vec(task)
            .map_err(|e| KVError::Metadata(format!("serialize GC task: {}", e)))?;
        self.run_with_reconnect("reschedule GC task", |connection| {
            let _: () = redis::cmd("ZREM")
                .arg(self.gc_inflight_key())
                .arg(&task_key)
                .query(connection)?;
            let _: () = redis::cmd("HSET")
                .arg(&task_key)
                .arg("payload")
                .arg(&payload)
                .query(connection)?;
            redis::cmd("ZADD")
                .arg(self.gc_due_key())
                .arg(task.not_before)
                .arg(&task_key)
                .query::<()>(connection)
        })
    }

    fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        let redis_key = self.block_key(key);
        let bytes = self.run_with_reconnect("get_block", |connection| {
            connection.get::<_, Option<Vec<u8>>>(&redis_key)
        })?;
        bytes.as_deref().map(Self::deserialize).transpose()
    }

    fn delete_block(&self, key: &str) -> Result<()> {
        let redis_key = self.block_key(key);
        self.run_with_reconnect("delete_block", |connection| {
            connection.del::<_, ()>(&redis_key)
        })
    }

    fn delete_block_if_matches(&self, key: &str, expected: &BlockMeta) -> Result<bool> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let redis_key = self.block_key(key);
        let expected_generation = expected.object_generation;
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local meta = redis.call("GET", KEYS[1])
            if meta then
                local ok, decoded = pcall(cjson.decode, meta)
                if ok and type(decoded) == "table" and tonumber(decoded["object_generation"]) == tonumber(ARGV[1]) then
                    redis.call("DEL", KEYS[1])
                    return 1
                end
            end
            return 0
            "#,
            )
        });
        let deleted = self.run_with_reconnect("delete_block_if_matches", |connection| {
            script
                .key(&redis_key)
                .arg(expected_generation)
                .invoke::<i32>(connection)
        })?;
        Ok(deleted == 1)
    }

    fn exists_block(&self, key: &str) -> Result<bool> {
        let redis_key = self.block_key(key);
        self.run_with_reconnect("exists_block", |connection| connection.exists(&redis_key))
    }

    fn next_generation(&self, key: &str) -> Result<u64> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let block_key = self.block_key(key);
        let generation_key = self.generation_key(key);
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local meta = redis.call("GET", KEYS[1])
            local current = tonumber(redis.call("GET", KEYS[2]) or "0")
            local base = current
            if meta then
                local ok, decoded = pcall(cjson.decode, meta)
                if ok and type(decoded) == "table" and decoded["object_generation"] then
                    local old_generation = tonumber(decoded["object_generation"]) or 0
                    if old_generation > base then
                        base = old_generation
                    end
                end
            end
            local next_generation = base + 1
            redis.call("SET", KEYS[2], next_generation)
            return next_generation
            "#,
            )
        });
        self.run_with_reconnect("next_generation", |connection| {
            script
                .key(&block_key)
                .key(&generation_key)
                .invoke::<u64>(connection)
        })
    }
}

#[cfg(test)]
#[derive(Default, Clone)]
struct MemoryMetadataBackend {
    inner: Arc<Mutex<MemoryMetadataInner>>,
}

#[cfg(test)]
#[derive(Default)]
struct MemoryMetadataInner {
    blocks: HashMap<String, Vec<u8>>,
    generations: HashMap<String, u64>,
    gc_tasks: HashMap<String, GcTask>,
    gc_leases: HashMap<String, i64>,
    fail_next_puts: usize,
}

#[cfg(test)]
impl MemoryMetadataBackend {
    fn for_url(url: &str) -> Self {
        static STORES: OnceLock<Mutex<HashMap<String, Arc<Mutex<MemoryMetadataInner>>>>> =
            OnceLock::new();
        let mut stores = STORES.get_or_init(|| Mutex::new(HashMap::new())).lock();
        let inner = stores
            .entry(url.to_string())
            .or_insert_with(|| Arc::new(Mutex::new(MemoryMetadataInner::default())))
            .clone();
        Self { inner }
    }

    fn serialize(meta: &BlockMeta) -> Result<Vec<u8>> {
        serde_json::to_vec(meta).map_err(|e| KVError::Metadata(format!("serialize: {}", e)))
    }

    fn deserialize(bytes: &[u8]) -> Result<BlockMeta> {
        serde_json::from_slice(bytes).map_err(|e| KVError::Metadata(format!("deserialize: {}", e)))
    }

    fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        let mut inner = self.inner.lock();
        if inner.fail_next_puts > 0 {
            inner.fail_next_puts -= 1;
            return Err(KVError::Metadata("injected put failure".to_string()));
        }
        inner.blocks.insert(key.to_string(), Self::serialize(meta)?);
        Ok(())
    }

    fn put_block_if_absent(&self, key: &str, meta: &BlockMeta) -> Result<bool> {
        let mut inner = self.inner.lock();
        if inner.fail_next_puts > 0 {
            inner.fail_next_puts -= 1;
            return Err(KVError::Metadata("injected put failure".to_string()));
        }
        if inner.blocks.contains_key(key) {
            return Ok(false);
        }
        inner.blocks.insert(key.to_string(), Self::serialize(meta)?);
        Ok(true)
    }

    fn task_id(key: &str, meta: &BlockMeta) -> Result<String> {
        Ok(format!(
            "{}:g{}:l{}:{}",
            key, meta.object_generation, meta.layout_version, meta.content_etag
        ))
    }

    fn enqueue_gc(
        inner: &mut MemoryMetadataInner,
        key: &str,
        retired: BlockMeta,
        not_before: i64,
    ) -> Result<()> {
        let id = Self::task_id(key, &retired)?;
        inner.gc_tasks.insert(
            id.clone(),
            GcTask {
                id,
                key: key.to_string(),
                retired,
                not_before,
                attempts: 0,
            },
        );
        Ok(())
    }

    fn replace_block(
        &self,
        key: &str,
        meta: &BlockMeta,
        not_before: i64,
    ) -> Result<Option<BlockMeta>> {
        let mut inner = self.inner.lock();
        if inner.fail_next_puts > 0 {
            inner.fail_next_puts -= 1;
            return Err(KVError::Metadata("injected put failure".to_string()));
        }
        let old = inner
            .blocks
            .insert(key.to_string(), Self::serialize(meta)?)
            .as_deref()
            .map(Self::deserialize)
            .transpose()?;
        if let Some(retired) = old.as_ref() {
            Self::enqueue_gc(&mut inner, key, retired.clone(), not_before)?;
        }
        Ok(old)
    }

    fn retire_block(&self, key: &str, not_before: i64) -> Result<Option<BlockMeta>> {
        let mut inner = self.inner.lock();
        let old = inner
            .blocks
            .remove(key)
            .as_deref()
            .map(Self::deserialize)
            .transpose()?;
        if let Some(retired) = old.as_ref() {
            Self::enqueue_gc(&mut inner, key, retired.clone(), not_before)?;
        }
        Ok(old)
    }

    fn same_version(actual: &BlockMeta, expected: &BlockMeta) -> bool {
        actual.object_handle == expected.object_handle
            && actual.object_generation == expected.object_generation
            && actual.layout_version == expected.layout_version
            && actual.content_etag == expected.content_etag
            && actual.size == expected.size
    }

    fn retire_block_if_matches(
        &self,
        key: &str,
        expected: &BlockMeta,
        not_before: i64,
    ) -> Result<bool> {
        let mut inner = self.inner.lock();
        let current = inner
            .blocks
            .get(key)
            .map(|bytes| Self::deserialize(bytes))
            .transpose()?;
        let Some(current) = current else {
            return Ok(false);
        };
        if !Self::same_version(&current, expected) {
            return Ok(false);
        }
        inner.blocks.remove(key);
        Self::enqueue_gc(&mut inner, key, current, not_before)?;
        Ok(true)
    }

    fn take_due_gc_tasks(&self, now: i64, limit: usize, lease_seconds: u64) -> Result<Vec<GcTask>> {
        let mut inner = self.inner.lock();
        inner.gc_leases.retain(|_, lease_until| *lease_until > now);
        let ids = inner
            .gc_tasks
            .iter()
            .filter(|(id, task)| task.not_before <= now && !inner.gc_leases.contains_key(*id))
            .map(|(id, _)| id.clone())
            .take(limit)
            .collect::<Vec<_>>();
        let tasks = ids
            .iter()
            .filter_map(|id| inner.gc_tasks.get(id).cloned())
            .collect();
        let lease_until = now.saturating_add(lease_seconds as i64);
        for id in ids {
            inner.gc_leases.insert(id, lease_until);
        }
        Ok(tasks)
    }

    fn complete_gc_task(&self, task_id: &str) -> Result<()> {
        let mut inner = self.inner.lock();
        inner.gc_tasks.remove(task_id);
        inner.gc_leases.remove(task_id);
        Ok(())
    }

    fn reschedule_gc_task(&self, task: &GcTask) -> Result<()> {
        let mut inner = self.inner.lock();
        inner.gc_leases.remove(&task.id);
        inner.gc_tasks.insert(task.id.clone(), task.clone());
        Ok(())
    }

    fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        self.inner
            .lock()
            .blocks
            .get(key)
            .map(|bytes| Self::deserialize(bytes))
            .transpose()
    }

    fn delete_block(&self, key: &str) -> Result<()> {
        self.inner.lock().blocks.remove(key);
        Ok(())
    }

    fn delete_block_if_matches(&self, key: &str, expected: &BlockMeta) -> Result<bool> {
        let mut inner = self.inner.lock();
        if let Some(bytes) = inner.blocks.get(key) {
            let stored = Self::deserialize(bytes)?;
            if stored.object_generation == expected.object_generation {
                inner.blocks.remove(key);
                return Ok(true);
            }
        }
        Ok(false)
    }

    fn exists_block(&self, key: &str) -> Result<bool> {
        Ok(self.inner.lock().blocks.contains_key(key))
    }

    fn next_generation(&self, key: &str) -> Result<u64> {
        let mut inner = self.inner.lock();
        let current = inner.generations.get(key).copied().unwrap_or(0);
        let old_generation = inner
            .blocks
            .get(key)
            .map(|bytes| Self::deserialize(bytes))
            .transpose()?
            .map(|meta| meta.object_generation)
            .unwrap_or(0);
        let next = current.max(old_generation) + 1;
        inner.generations.insert(key.to_string(), next);
        Ok(next)
    }

    fn fail_next_put(&self) {
        self.inner.lock().fail_next_puts += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config(name: &str) -> Config {
        let mut cfg = Config::default();
        cfg.metadata.redis_url = format!("memory://metadata-{}", name);
        cfg
    }

    fn meta() -> BlockMeta {
        BlockMeta {
            device_id: 0,
            file_path: "/tmp/x.bin".to_string(),
            size: 1024,
            object_handle: "handle-1".to_string(),
            object_generation: 1,
            content_etag: "etag-1".to_string(),
            layout_version: 1,
            created_at: 100,
            last_accessed_at: 100,
            ttl_seconds: 0,
            num_tokens: 256,
            num_layers: 1,
            dtype: "bfloat16".to_string(),
            compressed: false,
            striping: None,
        }
    }

    #[test]
    fn test_block_meta_roundtrip() {
        let svc = MetadataService::new(&test_config("roundtrip")).unwrap();
        let meta = meta();
        svc.put_block("k1", &meta).unwrap();
        let got = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(got.size, 1024);
        assert_eq!(got.object_handle, "handle-1");
        assert_eq!(got.object_generation, 1);
        assert_eq!(got.content_etag, "etag-1");
        assert_eq!(got.layout_version, 1);
        assert!(got.striping.is_none());
        assert!(svc.exists_block("k1").unwrap());
        svc.delete_block("k1").unwrap();
        assert!(!svc.exists_block("k1").unwrap());
    }

    #[test]
    fn put_block_if_absent_commits_only_once() {
        let svc = MetadataService::new(&test_config("if-absent")).unwrap();
        let mut first = meta();
        first.object_generation = 1;
        let mut second = meta();
        second.object_generation = 2;

        assert!(svc.put_block_if_absent("k1", &first).unwrap());
        assert!(!svc.put_block_if_absent("k1", &second).unwrap());

        let got = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(got.object_generation, 1);
    }

    #[test]
    fn delete_block_if_matches_keeps_newer_metadata() {
        let svc = MetadataService::new(&test_config("compare-delete")).unwrap();
        let mut first = meta();
        first.object_generation = 1;
        let mut second = meta();
        second.object_generation = 2;

        svc.put_block("k1", &second).unwrap();

        assert!(!svc.delete_block_if_matches("k1", &first).unwrap());
        assert_eq!(svc.get_block("k1").unwrap().unwrap().object_generation, 2);
        assert!(svc.delete_block_if_matches("k1", &second).unwrap());
        assert!(svc.get_block("k1").unwrap().is_none());
    }

    #[test]
    fn delete_block_if_matches_uses_generation_identity() {
        let svc = MetadataService::new(&test_config("compare-delete-generation")).unwrap();
        let stored = meta();
        let mut expected = meta();
        expected.content_etag = "etag-from-older-binary".to_string();
        expected.layout_version = 99;

        svc.put_block("k1", &stored).unwrap();

        assert!(svc.delete_block_if_matches("k1", &expected).unwrap());
        assert!(svc.get_block("k1").unwrap().is_none());
    }

    #[test]
    fn injected_put_failure_is_one_shot() {
        let svc = MetadataService::new(&test_config("inject-put")).unwrap();
        let meta = meta();

        svc.fail_next_put_for_test();
        assert!(svc.put_block("k1", &meta).is_err());
        svc.put_block("k1", &meta).unwrap();

        assert!(svc.exists_block("k1").unwrap());
    }

    #[test]
    fn next_generation_is_monotonic() {
        let svc = MetadataService::new(&test_config("generation")).unwrap();
        assert_eq!(svc.next_generation("k1").unwrap(), 1);
        assert_eq!(svc.next_generation("k1").unwrap(), 2);

        let mut meta = meta();
        meta.object_generation = 10;
        svc.put_block("k1", &meta).unwrap();
        assert_eq!(svc.next_generation("k1").unwrap(), 11);
    }

    #[test]
    fn replace_block_enqueues_the_superseded_generation() {
        let svc = MetadataService::new(&test_config("replace-gc")).unwrap();
        let first = meta();
        let mut second = meta();
        second.object_generation = 2;
        second.object_handle = "handle-2".to_string();
        second.content_etag = "etag-2".to_string();

        svc.put_block("k1", &first).unwrap();
        let retired = svc.replace_block("k1", &second, 100).unwrap().unwrap();
        assert_eq!(retired.object_generation, first.object_generation);
        assert_eq!(retired.object_handle, first.object_handle);
        let current = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(current.object_generation, second.object_generation);
        assert_eq!(current.object_handle, second.object_handle);

        let tasks = svc.take_due_gc_tasks(100, 10, 10).unwrap();
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].key, "k1");
        assert_eq!(tasks[0].retired.object_generation, 1);
    }

    #[test]
    fn retiring_a_block_preserves_the_generation_counter() {
        let svc = MetadataService::new(&test_config("retire-generation")).unwrap();
        let first = meta();
        assert_eq!(svc.next_generation("k1").unwrap(), 1);
        svc.put_block("k1", &first).unwrap();

        let retired = svc.retire_block("k1", 100).unwrap().unwrap();
        assert_eq!(retired.object_generation, first.object_generation);
        assert!(svc.get_block("k1").unwrap().is_none());
        assert_eq!(svc.next_generation("k1").unwrap(), 2);
    }

    #[test]
    fn stale_retire_does_not_remove_a_newer_identity() {
        let svc = MetadataService::new(&test_config("stale-retire")).unwrap();
        let first = meta();
        let mut replacement = first.clone();
        replacement.content_etag = "replacement-etag".to_string();
        replacement.object_handle = "replacement-handle".to_string();

        svc.put_block("k1", &replacement).unwrap();
        assert!(!svc.retire_block_if_matches("k1", &first, 100).unwrap());
        let current = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(current.object_handle, replacement.object_handle);
        assert!(svc.take_due_gc_tasks(100, 10, 10).unwrap().is_empty());
    }

    #[test]
    fn expired_gc_lease_can_be_reclaimed() {
        let svc = MetadataService::new(&test_config("gc-lease")).unwrap();
        svc.put_block("k1", &meta()).unwrap();
        svc.retire_block("k1", 100).unwrap();

        let first = svc.take_due_gc_tasks(100, 1, 10).unwrap();
        assert_eq!(first.len(), 1);
        assert!(svc.take_due_gc_tasks(109, 1, 10).unwrap().is_empty());
        let recovered = svc.take_due_gc_tasks(110, 1, 10).unwrap();
        assert_eq!(recovered.len(), 1);
        assert_eq!(recovered[0].id, first[0].id);
    }

    #[test]
    fn block_meta_expiry_uses_created_at_and_positive_ttl() {
        let mut meta = meta();
        meta.created_at = 100;
        meta.ttl_seconds = 10;

        assert!(!meta.is_expired_at(109));
        assert!(meta.is_expired_at(110));

        meta.ttl_seconds = 0;
        assert!(!meta.is_expired_at(1_000));
    }
}
