//! Metadata Service — shared object metadata backed by Redis.

use crate::config::Config;
use crate::error::{KVError, Result};
use crate::metrics::Metrics;
use parking_lot::Mutex;
use redis::Commands;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::sync::OnceLock;
use std::time::Duration;
use std::time::Instant;

#[cfg(test)]
use std::collections::HashMap;

const BLOCK_META_SEGMENT: &str = "block_meta";
const GENERATION_SEGMENT: &str = "generation";

fn default_object_generation() -> u64 {
    1
}

fn default_layout_version() -> u64 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ChunkLocation {
    pub stripe_index: u32,
    pub node_id: String,
    pub grpc_endpoint: String,
    pub rdma_endpoint: String,
    pub device_id: u32,
    pub storage_handle: String,
    pub offset: u64,
    pub length: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StripingInfo {
    /// Chunk size (bytes)
    pub chunk_size: u64,
    /// device_id for each chunk, indexed by chunk 0..N
    pub chunk_devices: Vec<u32>,
    /// File path (absolute) for each chunk
    pub chunk_paths: Vec<String>,
    /// Total raw data size
    pub total_size: u64,
    /// Actual per-chunk placement frozen at write time.
    ///
    /// May be empty for legacy metadata; when empty, fall back to local-node
    /// placement derived from chunk_paths/chunk_devices.
    #[serde(default)]
    pub chunk_locations: Vec<ChunkLocation>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockMeta {
    pub device_id: u32,
    pub file_path: String,
    pub size: u64,
    /// Opaque read handle generated by the server. Clients only pass it back;
    /// they do not interpret the internal format.
    #[serde(default)]
    pub object_handle: String,
    /// Content generation of the same object key. New objects start at 1 and
    /// increment on overwrite.
    #[serde(default = "default_object_generation")]
    pub object_generation: u64,
    /// Content identity token generated at write time. A lightweight etag —
    /// GET requests are not required to recompute a hash over the whole object.
    #[serde(default)]
    pub content_etag: String,
    /// Physical layout version. Increments when rebalance/migration changes
    /// only the layout; it does not indicate content changes.
    #[serde(default = "default_layout_version")]
    pub layout_version: u64,
    pub created_at: i64,
    pub last_accessed_at: i64,
    pub ttl_seconds: i64,
    pub num_tokens: i32,
    pub num_layers: i32,
    pub dtype: String,
    pub compressed: bool,
    /// When Some, the value is striped across multiple chunks
    #[serde(default)]
    pub striping: Option<StripingInfo>,
}

enum MetadataBackend {
    Redis(RedisMetadataBackend),
    #[cfg(test)]
    Memory(MemoryMetadataBackend),
}

pub struct MetadataService {
    backend: MetadataBackend,
}

impl MetadataService {
    pub fn new(config: &Config) -> Result<Self> {
        Self::new_with_metrics(config, None)
    }

    pub fn new_with_metrics(config: &Config, metrics: Option<Arc<Metrics>>) -> Result<Self> {
        #[cfg(test)]
        if config.metadata.redis_url.starts_with("memory://") {
            return Ok(Self {
                backend: MetadataBackend::Memory(MemoryMetadataBackend::for_url(
                    &config.metadata.redis_url,
                )),
            });
        }

        Ok(Self {
            backend: MetadataBackend::Redis(RedisMetadataBackend::new(config, metrics)?),
        })
    }

    // ===== Block Meta =====

    pub fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.put_block(key, meta),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.put_block(key, meta),
        }
    }

    pub fn put_block_if_absent(&self, key: &str, meta: &BlockMeta) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.put_block_if_absent(key, meta),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.put_block_if_absent(key, meta),
        }
    }

    pub fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.get_block(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.get_block(key),
        }
    }

    pub fn delete_block(&self, key: &str) -> Result<()> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.delete_block(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.delete_block(key),
        }
    }

    /// Delete metadata only when the stored value still matches the expected object metadata.
    pub fn delete_block_if_matches(&self, key: &str, expected: &BlockMeta) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.delete_block_if_matches(key, expected),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.delete_block_if_matches(key, expected),
        }
    }

    pub fn exists_block(&self, key: &str) -> Result<bool> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.exists_block(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.exists_block(key),
        }
    }

    pub fn next_generation(&self, key: &str) -> Result<u64> {
        match &self.backend {
            MetadataBackend::Redis(backend) => backend.next_generation(key),
            #[cfg(test)]
            MetadataBackend::Memory(backend) => backend.next_generation(key),
        }
    }

    #[cfg(test)]
    pub fn fail_next_put_for_test(&self) {
        if let MetadataBackend::Memory(backend) = &self.backend {
            backend.fail_next_put();
        }
    }
}

struct RedisMetadataBackend {
    client: redis::Client,
    prefix: String,
    connect_timeout: Duration,
    command_timeout: Duration,
    connection: Mutex<redis::Connection>,
    metrics: Option<Arc<Metrics>>,
}

impl RedisMetadataBackend {
    fn new(config: &Config, metrics: Option<Arc<Metrics>>) -> Result<Self> {
        let client = redis::Client::open(config.metadata.redis_url.as_str())
            .map_err(|e| KVError::Metadata(format!("open Redis client: {}", e)))?;
        let connect_timeout = Duration::from_millis(config.metadata.redis_connect_timeout_ms);
        let command_timeout = Duration::from_millis(config.metadata.redis_command_timeout_ms);
        let mut connection = Self::connect(&client, connect_timeout, command_timeout)?;
        redis::cmd("PING")
            .query::<String>(&mut connection)
            .map_err(|e| KVError::Metadata(format!("ping Redis metadata store: {}", e)))?;

        Ok(Self {
            client,
            prefix: config.metadata.redis_key_prefix.clone(),
            connect_timeout,
            command_timeout,
            connection: Mutex::new(connection),
            metrics,
        })
    }

    fn connect(
        client: &redis::Client,
        connect_timeout: Duration,
        command_timeout: Duration,
    ) -> Result<redis::Connection> {
        let connection = client
            .get_connection_with_timeout(connect_timeout)
            .map_err(|e| {
                KVError::Metadata(format!(
                    "connect Redis metadata store within {} ms: {}",
                    connect_timeout.as_millis(),
                    e
                ))
            })?;
        connection
            .set_read_timeout(Some(command_timeout))
            .map_err(|e| KVError::Metadata(format!("set Redis read timeout: {}", e)))?;
        connection
            .set_write_timeout(Some(command_timeout))
            .map_err(|e| KVError::Metadata(format!("set Redis write timeout: {}", e)))?;
        Ok(connection)
    }

    fn run_with_reconnect<T, F>(&self, op: &str, mut command: F) -> Result<T>
    where
        F: FnMut(&mut redis::Connection) -> redis::RedisResult<T>,
    {
        let started = self.metrics.as_ref().map(|_| Instant::now());
        let mut connection = self.connection.lock();
        let result = match command(&mut connection) {
            Ok(value) => Ok(value),
            Err(first_error) => {
                tracing::warn!(
                    "Redis metadata command {} failed, reconnecting once: {}",
                    op,
                    first_error
                );
                if let Some(metrics) = &self.metrics {
                    metrics.record_metadata_reconnect();
                }
                match Self::connect(&self.client, self.connect_timeout, self.command_timeout) {
                    Ok(mut new_connection) => match command(&mut new_connection) {
                        Ok(value) => {
                            *connection = new_connection;
                            Ok(value)
                        }
                        Err(second_error) => Err(KVError::Metadata(format!(
                            "redis {} failed after reconnect: {}; first error: {}",
                            op, second_error, first_error
                        ))),
                    },
                    Err(reconnect_error) => Err(reconnect_error),
                }
            }
        };
        if let (Some(metrics), Some(started)) = (&self.metrics, started) {
            metrics.record_metadata_operation(
                op,
                if result.is_ok() { "ok" } else { "error" },
                started.elapsed().as_secs_f64(),
            );
        }
        result
    }

    fn block_key(&self, key: &str) -> String {
        format!("{}{}:{}", self.prefix, BLOCK_META_SEGMENT, key)
    }

    fn generation_key(&self, key: &str) -> String {
        format!("{}{}:{}", self.prefix, GENERATION_SEGMENT, key)
    }

    fn serialize(meta: &BlockMeta) -> Result<Vec<u8>> {
        serde_json::to_vec(meta).map_err(|e| KVError::Metadata(format!("serialize: {}", e)))
    }

    fn deserialize(bytes: &[u8]) -> Result<BlockMeta> {
        serde_json::from_slice(bytes).map_err(|e| KVError::Metadata(format!("deserialize: {}", e)))
    }

    fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        let redis_key = self.block_key(key);
        let bytes = Self::serialize(meta)?;
        self.run_with_reconnect("put_block", |connection| {
            connection.set::<_, _, ()>(&redis_key, &bytes)
        })
    }

    fn put_block_if_absent(&self, key: &str, meta: &BlockMeta) -> Result<bool> {
        let redis_key = self.block_key(key);
        let bytes = Self::serialize(meta)?;
        let result = self.run_with_reconnect("put_block_if_absent", |connection| {
            redis::cmd("SET")
                .arg(&redis_key)
                .arg(&bytes)
                .arg("NX")
                .query::<Option<String>>(connection)
        })?;
        Ok(result.is_some())
    }

    fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        let redis_key = self.block_key(key);
        let bytes = self.run_with_reconnect("get_block", |connection| {
            connection.get::<_, Option<Vec<u8>>>(&redis_key)
        })?;
        bytes.as_deref().map(Self::deserialize).transpose()
    }

    fn delete_block(&self, key: &str) -> Result<()> {
        let redis_key = self.block_key(key);
        self.run_with_reconnect("delete_block", |connection| {
            connection.del::<_, ()>(&redis_key)
        })
    }

    fn delete_block_if_matches(&self, key: &str, expected: &BlockMeta) -> Result<bool> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let redis_key = self.block_key(key);
        let expected_generation = expected.object_generation;
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local meta = redis.call("GET", KEYS[1])
            if meta then
                local ok, decoded = pcall(cjson.decode, meta)
                if ok and type(decoded) == "table" and tonumber(decoded["object_generation"]) == tonumber(ARGV[1]) then
                    redis.call("DEL", KEYS[1])
                    return 1
                end
            end
            return 0
            "#,
            )
        });
        let deleted = self.run_with_reconnect("delete_block_if_matches", |connection| {
            script
                .key(&redis_key)
                .arg(expected_generation)
                .invoke::<i32>(connection)
        })?;
        Ok(deleted == 1)
    }

    fn exists_block(&self, key: &str) -> Result<bool> {
        let redis_key = self.block_key(key);
        self.run_with_reconnect("exists_block", |connection| connection.exists(&redis_key))
    }

    fn next_generation(&self, key: &str) -> Result<u64> {
        static SCRIPT: OnceLock<redis::Script> = OnceLock::new();
        let block_key = self.block_key(key);
        let generation_key = self.generation_key(key);
        let script = SCRIPT.get_or_init(|| {
            redis::Script::new(
                r#"
            local meta = redis.call("GET", KEYS[1])
            local current = tonumber(redis.call("GET", KEYS[2]) or "0")
            local base = current
            if meta then
                local ok, decoded = pcall(cjson.decode, meta)
                if ok and type(decoded) == "table" and decoded["object_generation"] then
                    local old_generation = tonumber(decoded["object_generation"]) or 0
                    if old_generation > base then
                        base = old_generation
                    end
                end
            end
            local next_generation = base + 1
            redis.call("SET", KEYS[2], next_generation)
            return next_generation
            "#,
            )
        });
        self.run_with_reconnect("next_generation", |connection| {
            script
                .key(&block_key)
                .key(&generation_key)
                .invoke::<u64>(connection)
        })
    }
}

#[cfg(test)]
#[derive(Default, Clone)]
struct MemoryMetadataBackend {
    inner: Arc<Mutex<MemoryMetadataInner>>,
}

#[cfg(test)]
#[derive(Default)]
struct MemoryMetadataInner {
    blocks: HashMap<String, Vec<u8>>,
    generations: HashMap<String, u64>,
    fail_next_puts: usize,
}

#[cfg(test)]
impl MemoryMetadataBackend {
    fn for_url(url: &str) -> Self {
        static STORES: OnceLock<Mutex<HashMap<String, Arc<Mutex<MemoryMetadataInner>>>>> =
            OnceLock::new();
        let mut stores = STORES.get_or_init(|| Mutex::new(HashMap::new())).lock();
        let inner = stores
            .entry(url.to_string())
            .or_insert_with(|| Arc::new(Mutex::new(MemoryMetadataInner::default())))
            .clone();
        Self { inner }
    }

    fn serialize(meta: &BlockMeta) -> Result<Vec<u8>> {
        serde_json::to_vec(meta).map_err(|e| KVError::Metadata(format!("serialize: {}", e)))
    }

    fn deserialize(bytes: &[u8]) -> Result<BlockMeta> {
        serde_json::from_slice(bytes).map_err(|e| KVError::Metadata(format!("deserialize: {}", e)))
    }

    fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        let mut inner = self.inner.lock();
        if inner.fail_next_puts > 0 {
            inner.fail_next_puts -= 1;
            return Err(KVError::Metadata("injected put failure".to_string()));
        }
        inner.blocks.insert(key.to_string(), Self::serialize(meta)?);
        Ok(())
    }

    fn put_block_if_absent(&self, key: &str, meta: &BlockMeta) -> Result<bool> {
        let mut inner = self.inner.lock();
        if inner.fail_next_puts > 0 {
            inner.fail_next_puts -= 1;
            return Err(KVError::Metadata("injected put failure".to_string()));
        }
        if inner.blocks.contains_key(key) {
            return Ok(false);
        }
        inner.blocks.insert(key.to_string(), Self::serialize(meta)?);
        Ok(true)
    }

    fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        self.inner
            .lock()
            .blocks
            .get(key)
            .map(|bytes| Self::deserialize(bytes))
            .transpose()
    }

    fn delete_block(&self, key: &str) -> Result<()> {
        self.inner.lock().blocks.remove(key);
        Ok(())
    }

    fn delete_block_if_matches(&self, key: &str, expected: &BlockMeta) -> Result<bool> {
        let mut inner = self.inner.lock();
        if let Some(bytes) = inner.blocks.get(key) {
            let stored = Self::deserialize(bytes)?;
            if stored.object_generation == expected.object_generation {
                inner.blocks.remove(key);
                return Ok(true);
            }
        }
        Ok(false)
    }

    fn exists_block(&self, key: &str) -> Result<bool> {
        Ok(self.inner.lock().blocks.contains_key(key))
    }

    fn next_generation(&self, key: &str) -> Result<u64> {
        let mut inner = self.inner.lock();
        let current = inner.generations.get(key).copied().unwrap_or(0);
        let old_generation = inner
            .blocks
            .get(key)
            .map(|bytes| Self::deserialize(bytes))
            .transpose()?
            .map(|meta| meta.object_generation)
            .unwrap_or(0);
        let next = current.max(old_generation) + 1;
        inner.generations.insert(key.to_string(), next);
        Ok(next)
    }

    fn fail_next_put(&self) {
        self.inner.lock().fail_next_puts += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config(name: &str) -> Config {
        let mut cfg = Config::default();
        cfg.metadata.redis_url = format!("memory://metadata-{}", name);
        cfg
    }

    fn meta() -> BlockMeta {
        BlockMeta {
            device_id: 0,
            file_path: "/tmp/x.bin".to_string(),
            size: 1024,
            object_handle: "handle-1".to_string(),
            object_generation: 1,
            content_etag: "etag-1".to_string(),
            layout_version: 1,
            created_at: 100,
            last_accessed_at: 100,
            ttl_seconds: 0,
            num_tokens: 256,
            num_layers: 1,
            dtype: "bfloat16".to_string(),
            compressed: false,
            striping: None,
        }
    }

    #[test]
    fn test_block_meta_roundtrip() {
        let svc = MetadataService::new(&test_config("roundtrip")).unwrap();
        let meta = meta();
        svc.put_block("k1", &meta).unwrap();
        let got = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(got.size, 1024);
        assert_eq!(got.object_handle, "handle-1");
        assert_eq!(got.object_generation, 1);
        assert_eq!(got.content_etag, "etag-1");
        assert_eq!(got.layout_version, 1);
        assert!(got.striping.is_none());
        assert!(svc.exists_block("k1").unwrap());
        svc.delete_block("k1").unwrap();
        assert!(!svc.exists_block("k1").unwrap());
    }

    #[test]
    fn put_block_if_absent_commits_only_once() {
        let svc = MetadataService::new(&test_config("if-absent")).unwrap();
        let mut first = meta();
        first.object_generation = 1;
        let mut second = meta();
        second.object_generation = 2;

        assert!(svc.put_block_if_absent("k1", &first).unwrap());
        assert!(!svc.put_block_if_absent("k1", &second).unwrap());

        let got = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(got.object_generation, 1);
    }

    #[test]
    fn delete_block_if_matches_keeps_newer_metadata() {
        let svc = MetadataService::new(&test_config("compare-delete")).unwrap();
        let mut first = meta();
        first.object_generation = 1;
        let mut second = meta();
        second.object_generation = 2;

        svc.put_block("k1", &second).unwrap();

        assert!(!svc.delete_block_if_matches("k1", &first).unwrap());
        assert_eq!(svc.get_block("k1").unwrap().unwrap().object_generation, 2);
        assert!(svc.delete_block_if_matches("k1", &second).unwrap());
        assert!(svc.get_block("k1").unwrap().is_none());
    }

    #[test]
    fn delete_block_if_matches_uses_generation_identity() {
        let svc = MetadataService::new(&test_config("compare-delete-generation")).unwrap();
        let stored = meta();
        let mut expected = meta();
        expected.content_etag = "etag-from-older-binary".to_string();
        expected.layout_version = 99;

        svc.put_block("k1", &stored).unwrap();

        assert!(svc.delete_block_if_matches("k1", &expected).unwrap());
        assert!(svc.get_block("k1").unwrap().is_none());
    }

    #[test]
    fn injected_put_failure_is_one_shot() {
        let svc = MetadataService::new(&test_config("inject-put")).unwrap();
        let meta = meta();

        svc.fail_next_put_for_test();
        assert!(svc.put_block("k1", &meta).is_err());
        svc.put_block("k1", &meta).unwrap();

        assert!(svc.exists_block("k1").unwrap());
    }

    #[test]
    fn next_generation_is_monotonic() {
        let svc = MetadataService::new(&test_config("generation")).unwrap();
        assert_eq!(svc.next_generation("k1").unwrap(), 1);
        assert_eq!(svc.next_generation("k1").unwrap(), 2);

        let mut meta = meta();
        meta.object_generation = 10;
        svc.put_block("k1", &meta).unwrap();
        assert_eq!(svc.next_generation("k1").unwrap(), 11);
    }
}
