//! Metadata Service — object metadata
//!
//! Backed by an embedded RocksDB. Cluster mode can be extended to etcd.

use crate::config::Config;
use crate::error::{KVError, Result};
use rocksdb::{ColumnFamilyDescriptor, Options, DB};
use serde::{Deserialize, Serialize};
use std::sync::Arc;

const CF_BLOCK_META: &str = "block_meta";

fn default_object_generation() -> u64 {
    1
}

fn default_layout_version() -> u64 {
    1
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ChunkLocation {
    pub stripe_index: u32,
    pub node_id: String,
    pub grpc_endpoint: String,
    pub rdma_endpoint: String,
    pub device_id: u32,
    pub storage_handle: String,
    pub offset: u64,
    pub length: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct StripingInfo {
    /// Chunk size (bytes)
    pub chunk_size: u64,
    /// device_id for each chunk, indexed by chunk 0..N
    pub chunk_devices: Vec<u32>,
    /// File path (absolute) for each chunk
    pub chunk_paths: Vec<String>,
    /// Total raw data size
    pub total_size: u64,
    /// Actual per-chunk placement frozen at write time.
    ///
    /// May be empty for legacy metadata; when empty, fall back to local-node
    /// placement derived from chunk_paths/chunk_devices.
    #[serde(default)]
    pub chunk_locations: Vec<ChunkLocation>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockMeta {
    pub device_id: u32,
    pub file_path: String,
    pub size: u64,
    /// Opaque read handle generated by the server. Clients only pass it back;
    /// they do not interpret the internal format.
    #[serde(default)]
    pub object_handle: String,
    /// Content generation of the same object key. New objects start at 1 and
    /// increment on overwrite.
    #[serde(default = "default_object_generation")]
    pub object_generation: u64,
    /// Content identity token generated at write time. A lightweight etag —
    /// GET requests are not required to recompute a hash over the whole object.
    #[serde(default)]
    pub content_etag: String,
    /// Physical layout version. Increments when rebalance/migration changes
    /// only the layout; it does not indicate content changes.
    #[serde(default = "default_layout_version")]
    pub layout_version: u64,
    pub created_at: i64,
    pub last_accessed_at: i64,
    pub ttl_seconds: i64,
    pub num_tokens: i32,
    pub num_layers: i32,
    pub dtype: String,
    pub compressed: bool,
    /// When Some, the value is striped across multiple chunks
    #[serde(default)]
    pub striping: Option<StripingInfo>,
}

pub struct MetadataService {
    db: Arc<DB>,
}

impl MetadataService {
    pub fn new(config: &Config) -> Result<Self> {
        std::fs::create_dir_all(&config.metadata.rocksdb_path)?;

        let mut opts = Options::default();
        opts.create_if_missing(true);
        opts.create_missing_column_families(true);

        let cfs = vec![ColumnFamilyDescriptor::new(
            CF_BLOCK_META,
            Options::default(),
        )];

        let db = DB::open_cf_descriptors(&opts, &config.metadata.rocksdb_path, cfs)?;

        Ok(Self { db: Arc::new(db) })
    }

    // ===== Block Meta =====

    pub fn put_block(&self, key: &str, meta: &BlockMeta) -> Result<()> {
        let cf = self
            .db
            .cf_handle(CF_BLOCK_META)
            .ok_or_else(|| KVError::Metadata("CF block_meta missing".to_string()))?;
        let bytes =
            serde_json::to_vec(meta).map_err(|e| KVError::Metadata(format!("serialize: {}", e)))?;
        self.db.put_cf(&cf, key.as_bytes(), bytes)?;
        Ok(())
    }

    pub fn get_block(&self, key: &str) -> Result<Option<BlockMeta>> {
        let cf = self
            .db
            .cf_handle(CF_BLOCK_META)
            .ok_or_else(|| KVError::Metadata("CF block_meta missing".to_string()))?;
        match self.db.get_cf(&cf, key.as_bytes())? {
            Some(bytes) => {
                let meta: BlockMeta = serde_json::from_slice(&bytes)
                    .map_err(|e| KVError::Metadata(format!("deserialize: {}", e)))?;
                Ok(Some(meta))
            }
            None => Ok(None),
        }
    }

    pub fn delete_block(&self, key: &str) -> Result<()> {
        let cf = self
            .db
            .cf_handle(CF_BLOCK_META)
            .ok_or_else(|| KVError::Metadata("CF block_meta missing".to_string()))?;
        self.db.delete_cf(&cf, key.as_bytes())?;
        Ok(())
    }

    pub fn exists_block(&self, key: &str) -> Result<bool> {
        Ok(self.get_block(key)?.is_some())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;
    use tempfile::TempDir;

    fn test_config(dir: &Path) -> Config {
        let mut cfg = Config::default();
        cfg.metadata.rocksdb_path = dir.to_path_buf();
        cfg
    }

    #[test]
    fn test_block_meta_roundtrip() {
        let tmp = TempDir::new().unwrap();
        let svc = MetadataService::new(&test_config(tmp.path())).unwrap();
        let meta = BlockMeta {
            device_id: 0,
            file_path: "/tmp/x.bin".to_string(),
            size: 1024,
            object_handle: "handle-1".to_string(),
            object_generation: 1,
            content_etag: "etag-1".to_string(),
            layout_version: 1,
            created_at: 100,
            last_accessed_at: 100,
            ttl_seconds: 0,
            num_tokens: 256,
            num_layers: 1,
            dtype: "bfloat16".to_string(),
            compressed: false,
            striping: None,
        };
        svc.put_block("k1", &meta).unwrap();
        let got = svc.get_block("k1").unwrap().unwrap();
        assert_eq!(got.size, 1024);
        assert_eq!(got.object_handle, "handle-1");
        assert_eq!(got.object_generation, 1);
        assert_eq!(got.content_etag, "etag-1");
        assert_eq!(got.layout_version, 1);
        assert!(got.striping.is_none());
        assert!(svc.exists_block("k1").unwrap());
        svc.delete_block("k1").unwrap();
        assert!(!svc.exists_block("k1").unwrap());
    }
}
